name: Haskell CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest,macOS-latest]
        resolver:
          - "--resolver lts-12"
          - "--resolver lts-13"
          - "--resolver nightly"
          - ""
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: mstksg/setup-stack@master
    - uses: mstksg/get-package@master
      with:
        apt-get: libblas-dev liblapack-dev
    - name: Install stack dependencies
      run: stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
      env:
        ARGS: ${{ matrix.resolver }}
    - name: Build
      run: |
        stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
      env:
        ARGS: ${{ matrix.resolver }}
