name: Haskell CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest,macOS-latest]
        plan:
        - { build: stack, resolver: "--resolver lts-12"  }
        - { build: stack, resolver: "--resolver lts-14"  }
        - { build: stack, resolver: "--resolver nightly" }
        - { build: stack, resolver: ""                   }
        - { build: cabal, ghc: 8.4.4 }
        - { build: cabal, ghc: 8.6.5 }
        - { build: cabal, ghc: 8.8.1 }

        # builder: [stack, cabal]
        # ghc:
        # - 8.4.4
        # - 8.6.5
        # - 8.8.1
        # - nightly
        # - default
      # include:
        # - { builder: stack, ghc: "8.4.4"  , resolver: "--resolver lts-12"  }
        # - { builder: stack, ghc: "8.6.5"  , resolver: "--resolver lts-14"  }
        # - { builder: stack, ghc: "nightly", resolver: "--resolver nightly" }
        # - { builder: stack, ghc: "default", resolver: ""                   }

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: mstksg/setup-stack@master
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.plan.ghc }}
        cabal-version: "3.0"
      if: matrix.plan.build == 'cabal'


    # get OS packages
    - uses: mstksg/get-package@master
      with:
        apt-get: libblas-dev liblapack-dev

    # install deps
    - name: Install stack dependencies
      run: stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
      env:
        ARGS: ${{ matrix.resolver }}

    # build
    - name: Build with Stack
      run: stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
      env:
        ARGS: ${{ matrix.plan.resolver }}
      if: matrix.plan.build == 'stack'

