name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install stack
      run: |
        # export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
        # export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
        curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - name: Install dependencies
      run: stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
      # run: cabal install --only-dependencies --enable-tests
    - name: Build
      run: stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
      # run: |
      #   cabal configure --enable-tests
      #   cabal build
    # - name: Run tests
    #   run: cabal test
